version: "3.8"

services:
  nbta-frontend:
    image: nbta-frontend:latest
    container_name: nbta-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - nbta-backend
    environment:
      - REACT_APP_API_URL=https://app.nbtecha.com
    networks:
      - nbta-network

  nbta-backend:
    image: nbta-backend:latest
    container_name: nbta-backend
    restart: always
    ports:
      - "3001:3001"  # Map container's port 3000 to host port 3001
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - nbta-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - nbta-network

volumes:
  mongo-data:

networks:
  nbta-network:
    driver: bridge
